/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class retromachines_rboy_RBoy */

#ifndef _Included_retromachines_rboy_RBoy
#define _Included_retromachines_rboy_RBoy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     retromachines_rboy_RBoy
 * Method:    construct_cpu
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_retromachines_rboy_RBoy_construct_1cpu
  (JNIEnv *, jclass, jstring);

/*
 * Class:     retromachines_rboy_RBoy
 * Method:    run_cpu
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_retromachines_rboy_RBoy_run_1cpu
  (JNIEnv *, jclass, jlong);

/*
 * Class:     retromachines_rboy_RBoy
 * Method:    get_gpu_data
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_retromachines_rboy_RBoy_get_1gpu_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     retromachines_rboy_RBoy
 * Method:    send_event
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_retromachines_rboy_RBoy_send_1event
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
