language: rust

rust:
  - stable

sudo: false

addons:
  apt:
    packages:
      - libasound2-dev

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - make debug
  - make test
