[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
blip_buf = ">=0.1.3"
jni = "0.21.1"
cpal = "0.14"

[[bin]]
name = "rboy"
test = false
doc = false
